import Foundation

enum L {
    private static let translations: [String: [String: String]] = [
        "cs": [
        "services.header": "Stav služeb",
        "unit.billion": "mld.",
        "unit.million": "mil.",
        "unit.thousand": "tis.",
        "error.claude_not_found": "Claude Code se nepodařilo najít",
        "error.codex_not_found": "Codex CLI se nepodařilo najít",
        "bar.style.percentage": "Procento",
        "bar.style.compact": "Kompaktní",
        "bar.style.progressBar": "Pruh",
        "bar.style.battery": "Baterie",
        "bar.style.iconWithBar": "Ikona s pruhem",
        "day.mon": "po",
        "day.tue": "út",
        "day.wed": "st",
        "day.thu": "čt",
        "day.fri": "pá",
        "day.sat": "so",
        "day.sun": "ne",
            "header.title": "AIPulse",
            "header.working_status": "Vše funguje",
            "header.service_issue": "Problém se službou",
            "header.refresh_tooltip": "Aktualizovat data",
            "header.settings_tooltip": "Nastavení",

            "donut.session_window": "5hodinové okno",
            "donut.weekly_limit": "Týdenní limit",

            "limits.no_limits": "Limity nejsou k dispozici",
            "limits.session": "Session",
            "limits.session_label": "5hodinové okno",
            "limits.weekly": "Týdenní",
            "limits.weekly_label": "všechny modely",

            "reset.resets_today": "Obnoví se dnes %@",
            "reset.resets": "Obnoví se %@",

            "day_chart.title": "Spotřeba po dnech (odhad z týdenního limitu)",
            "day_chart.optimum": "Optimum: %.0f %%",

            "models.title": "Modely (tento týden)",

            "footer.updated": "Aktualizováno: %@",

            "time_ago.just_now": "právě teď",
            "time_ago.minutes": "před %d min",
            "time_ago.hours": "před %d h",
            "time_ago.days": "před %d d",

            "error.data_unavailable": "Data nejsou dostupná",
            "error.run_collect": "Spustit sběr",
            "error.data_load_failed": "Data se nepodařilo načíst: %@",
            "error.config_save_failed": "Nepodařilo se uložit nastavení: %@",
            "error.unknown": "Neznámá chyba",
            "error.interval_failed": "Nepodařilo se nastavit interval: %@",
            "error.limits_timeout": "Načtení limitů trvalo příliš dlouho",
            "error.limits_failed": "Nepodařilo se načíst limity",
            "error.collect_start_failed": "Sběr dat se nepodařilo spustit: %@",
            "month.01": "led",
            "month.02": "úno",
            "month.03": "bře",
            "month.04": "dub",
            "month.05": "kvě",
            "month.06": "čvn",
            "month.07": "čvc",
            "month.08": "srp",
            "month.09": "zář",
            "month.10": "říj",
            "month.11": "lis",
            "month.12": "pro",

            "settings.title": "Nastavení AIPulse",
            "settings.general_title": "Obecné",
            "settings.login": "Přihlášení",
            "settings.history": "Historie",
            "settings.bar_appearance": "Vzhled lišty",
            "settings.language": "Jazyk",
            "settings.general": "Obecné",
            "settings.section.general": "Obecné",

            "settings.group.appearance": "Styl",
            "settings.group.behavior": "Chování",
            "settings.group.actions": "Akce",
            "login.provider_label": "Aktivní nástroj",
            "login.provider_claude": "Claude",
            "login.provider_codex": "Codex",
            "login.logged_in": "Přihlášen",
            "login.logged_out": "Nepřihlášen",
            "login.email_label": "E-mail",
            "login.subscription_label": "Typ předplatného",
            "login.logout_button": "Odhlásit se",
            "login.login_button": "Přihlásit se",
            "login.logout_confirm_title": "Potvrdit odhlášení",
            "login.logout_confirm_message": "Opravdu se chcete odhlásit?",
            "login.logout_cancel": "Zrušit",
            "login.codex_method": "Způsob přihlášení",
            "login.codex_account": "Účet",
            "login.in_progress": "Přihlašuji v prohlížeči…",
            "login.timed_out": "Přihlášení se nedokončilo",
            "history.period_days": "Dny",
            "history.period_weeks": "Týdny",
            "history.period_months": "Měsíce",
            "history.no_data": "Žádná data",
            "history.day_header": "Den",
            "history.week_header": "Týden",
            "history.month_header": "Měsíc",
            "history.tokens_header": "Tokeny",
            "history.price_header": "Cena",
            "history.total": "Celkem",
            "history.all_time": "Od začátku",

            "bar_appearance.title": "Vzhled lišty",
            "bar_appearance.style_label": "Styl",
            "bar_appearance.style_percentage": "Procento",
            "bar_appearance.style_compact": "Kompaktní",
            "bar_appearance.style_progress": "Pruh",
            "bar_appearance.style_battery": "Baterie",
            "bar_appearance.style_icon_bar": "Ikona s pruhem",
            "bar_appearance.display_label": "Co zobrazovat",
            "bar_appearance.metric_label": "Metrika",
            "bar_appearance.metric_weekly": "Procento",
            "bar_appearance.metric_session": "Session",
            "bar_appearance.metric_tokens": "Tokeny",

            "bar_appearance.color_legend": "Legenda barev prahů",
            "bar_appearance.color_under_50": "pod 50 % — zelená",
            "bar_appearance.color_50_74": "50 až 74 % — žlutá",
            "bar_appearance.color_75_89": "75 až 89 % — oranžová",
            "bar_appearance.color_over_90": "90 % a víc — červená",
            "language.interface_language": "Jazyk rozhraní",

            "general.startup": "Spouštět po přihlášení",
            "general.refresh_interval": "Aktualizovat každých",
            "general.refresh_5min": "5 minut",
            "general.refresh_10min": "10 minut",
            "general.refresh_15min": "15 minut",
            "general.refresh_30min": "30 minut",
            "general.refresh_60min": "60 minut",
            "general.work_days": "Pracovních dnů v týdnu",
            "general.update_button": "Aktualizovat data",
            "general.updating": "Stahuji…",
            "general.error_startup": "Chyba: %@",

            "services.title": "Stav služeb",
            "services.all_operational": "Všechny systémy fungují",
            "services.issues": "Problémy se službou",
            "services.no_incidents": "Žádné probíhající problémy",
            "services.ongoing_incidents": "Probíhající incidenty",
            "services.status_link": "status.claude.com",

            "settings.notifications": "Notifikace",
            "notifications.title": "Upozornění na výpadky",
            "notifications.empty": "Zatím nejsou známé žádné služby — počkej na první sběr dat.",
            "notifications.down_title": "Výpadek: %@",
            "notifications.up_title": "Zase v pořádku: %@",
            "notifications.provider_anthropic": "Anthropic",
            "notifications.provider_openai": "OpenAI",
            "notifications.select_all": "Vybrat vše",
            "notifications.select_none": "Zrušit výběr",

            "status.operational": "V pořádku",
            "status.degraded_performance": "Zpomalená odezva",
            "status.partial_outage": "Částečný výpadek",
            "status.major_outage": "Velký výpadek",
            "status.under_maintenance": "Probíhá údržba",
            "status.unknown": "Neznámý stav",
        ],
        "en": [
        "services.header": "Service status",
        "unit.billion": "B",
        "unit.million": "M",
        "unit.thousand": "K",
        "error.claude_not_found": "Could not find the Claude Code CLI",
        "error.codex_not_found": "Could not find the Codex CLI",
        "bar.style.percentage": "Percentage",
        "bar.style.compact": "Compact",
        "bar.style.progressBar": "Bar",
        "bar.style.battery": "Battery",
        "bar.style.iconWithBar": "Icon with bar",
        "day.mon": "Mon",
        "day.tue": "Tue",
        "day.wed": "Wed",
        "day.thu": "Thu",
        "day.fri": "Fri",
        "day.sat": "Sat",
        "day.sun": "Sun",
            "header.title": "AIPulse",
            "header.working_status": "Everything working",
            "header.service_issue": "Service issue",
            "header.refresh_tooltip": "Refresh data",
            "header.settings_tooltip": "Settings",

            "donut.session_window": "5-hour window",
            "donut.weekly_limit": "Weekly limit",

            "limits.no_limits": "Limits unavailable",
            "limits.session": "Session",
            "limits.session_label": "5-hour window",
            "limits.weekly": "Weekly",
            "limits.weekly_label": "all models",

            "reset.resets_today": "Resets today at %@",
            "reset.resets": "Resets at %@",

            "day_chart.title": "Consumption by day (estimated from weekly limit)",
            "day_chart.optimum": "Optimum: %.0f %%",

            "models.title": "Models (this week)",

            "footer.updated": "Updated: %@",

            "time_ago.just_now": "just now",
            "time_ago.minutes": "%d min ago",
            "time_ago.hours": "%d h ago",
            "time_ago.days": "%d d ago",

            "error.data_unavailable": "Data unavailable",
            "error.run_collect": "Run collection",
            "error.data_load_failed": "Could not load data: %@",
            "error.config_save_failed": "Could not save settings: %@",
            "error.unknown": "Unknown error",
            "error.interval_failed": "Could not change the interval: %@",
            "error.limits_timeout": "Fetching the limits took too long",
            "error.limits_failed": "Could not fetch the limits",
            "error.collect_start_failed": "Could not start the collection: %@",
            "month.01": "Jan",
            "month.02": "Feb",
            "month.03": "Mar",
            "month.04": "Apr",
            "month.05": "May",
            "month.06": "Jun",
            "month.07": "Jul",
            "month.08": "Aug",
            "month.09": "Sep",
            "month.10": "Oct",
            "month.11": "Nov",
            "month.12": "Dec",

            "settings.title": "AIPulse Settings",
            "settings.general_title": "General",
            "settings.login": "Login",
            "settings.history": "History",
            "settings.bar_appearance": "Bar Appearance",
            "settings.language": "Language",
            "settings.general": "General",
            "settings.section.general": "General",

            "settings.group.appearance": "Style",
            "settings.group.behavior": "Behavior",
            "settings.group.actions": "Actions",
            "login.provider_label": "Active tool",
            "login.provider_claude": "Claude",
            "login.provider_codex": "Codex",
            "login.logged_in": "Logged in",
            "login.logged_out": "Not logged in",
            "login.email_label": "Email",
            "login.subscription_label": "Subscription type",
            "login.logout_button": "Logout",
            "login.login_button": "Login",
            "login.logout_confirm_title": "Confirm logout",
            "login.logout_confirm_message": "Are you sure you want to logout?",
            "login.logout_cancel": "Cancel",
            "login.codex_method": "Sign-in method",
            "login.codex_account": "Account",
            "login.in_progress": "Signing in through the browser…",
            "login.timed_out": "The sign-in did not complete",
            "history.period_days": "Days",
            "history.period_weeks": "Weeks",
            "history.period_months": "Months",
            "history.no_data": "No data",
            "history.day_header": "Day",
            "history.week_header": "Week",
            "history.month_header": "Month",
            "history.tokens_header": "Tokens",
            "history.price_header": "Price",
            "history.total": "Total",
            "history.all_time": "All time",

            "bar_appearance.title": "Bar Appearance",
            "bar_appearance.style_label": "Style",
            "bar_appearance.style_percentage": "Percentage",
            "bar_appearance.style_compact": "Compact",
            "bar_appearance.style_progress": "Progress bar",
            "bar_appearance.style_battery": "Battery",
            "bar_appearance.style_icon_bar": "Icon with bar",
            "bar_appearance.display_label": "What to display",
            "bar_appearance.metric_label": "Metric",
            "bar_appearance.metric_weekly": "Percentage",
            "bar_appearance.metric_session": "Session",
            "bar_appearance.metric_tokens": "Tokens",

            "bar_appearance.color_legend": "Color threshold legend",
            "bar_appearance.color_under_50": "under 50% — green",
            "bar_appearance.color_50_74": "50 to 74% — yellow",
            "bar_appearance.color_75_89": "75 to 89% — orange",
            "bar_appearance.color_over_90": "90% and above — red",
            "language.interface_language": "Interface language",

            "general.startup": "Launch on login",
            "general.refresh_interval": "Refresh every",
            "general.refresh_5min": "5 minutes",
            "general.refresh_10min": "10 minutes",
            "general.refresh_15min": "15 minutes",
            "general.refresh_30min": "30 minutes",
            "general.refresh_60min": "60 minutes",
            "general.work_days": "Work days per week",
            "general.update_button": "Update data",
            "general.updating": "Downloading…",
            "general.error_startup": "Error: %@",

            "services.title": "Service Status",
            "services.all_operational": "All systems operational",
            "services.issues": "Service issues",
            "services.no_incidents": "No ongoing issues",
            "services.ongoing_incidents": "Ongoing incidents",
            "services.status_link": "status.claude.com",

            "settings.notifications": "Notifications",
            "notifications.title": "Outage alerts",
            "notifications.empty": "No services known yet - wait for the first collection.",
            "notifications.down_title": "Outage: %@",
            "notifications.up_title": "Back up: %@",
            "notifications.provider_anthropic": "Anthropic",
            "notifications.provider_openai": "OpenAI",
            "notifications.select_all": "Select all",
            "notifications.select_none": "Clear selection",

            "status.operational": "Operational",
            "status.degraded_performance": "Degraded performance",
            "status.partial_outage": "Partial outage",
            "status.major_outage": "Major outage",
            "status.under_maintenance": "Under maintenance",
            "status.unknown": "Unknown state",
        ]
    ]

    static func t(_ key: String, _ language: String = "cs") -> String {
        let lang = language.isEmpty || language == "cs" || language == "en" ? language : "cs"

        if let dict = translations[lang], let value = dict[key] {
            return value
        }

        if lang != "cs", let dict = translations["cs"], let value = dict[key] {
            return value
        }

        return key
    }
}
